# Site settings
title: "Alevtina Verbovetskaya"
email: alevtina@verbovetskaya.com
description: >-
  Librarian, knitter, vegan.
baseurl: ""
url: "https://verbovetskaya.com"

# Personal information
author:
  name: "Alevtina Verbovetskaya"
  bio: >-
    Librarian, knitter, vegan.
  gravatar_hash: "94a7df47fd5166da5bb92fc9d4108b26"  # MD5 of alevtina@verbovetskaya.com

# Social profiles
social:
  linkedin: https://www.linkedin.com/in/alevtina-verbovetskaya/
  github: alevtina
  email: alevtina@verbovetskaya.com
  mastodon: https://glammr.us/@alevtina

# Build settings
destination: /tmp/jekyll-site
markdown: kramdown
highlighter: rouge
theme: minima
excerpt_separator: "<!--more-->"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-webmention_io
  - jekyll-archives

# Tag archives
jekyll-archives:
  enabled:
    - tags
  layout: tag_archive
  permalinks:
    tag: /tags/:name/

# Webmentions
webmentions:
  username: verbovetskaya.com
  cache_folder: _data
  pages: false
  js: false
  templates:
    webmentions: _includes/webmentions/webmentions.html
    likes: _includes/webmentions/likes.html
    reposts: _includes/webmentions/reposts.html
    replies: _includes/webmentions/replies.html


# Collections
collections:
  reading:
    output: true
    permalink: /reading/:slug/
  knitting:
    output: true
    permalink: /knitting/:slug/

# jekyll-feed: main feed + reading feed + knitting feed
feed:
  collections:
    posts:
      path: "/feed.xml"
    reading:
      path: "/feed/reading.xml"
    knitting:
      path: "/feed/knitting.xml"

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /blog/:title/
  - scope:
      path: ""
      type: "reading"
    values:
      layout: "read"
  - scope:
      path: ""
      type: "knitting"
    values:
      layout: "knit"

